### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by ciyuanjing** [jiwoogit/Style-InDi#28]
Thank you for your excellent work, but I would like to ask how many graphics cards are needed to run the diffusers version of the code.

**Comment by jiwoogit** [comment]
Sorry for the late reply. Our work only requires a single GPU.

**Comment by ciyuanjing** [comment]
> Sorry for the late reply. Our work only requires a single GPU.

Thank you very much for your answer. I have solved this problem.
